// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightLinksValidator from 'starlight-links-validator';

// https://astro.build/config
export default defineConfig({
	// GitHub Pages — see docs/adr/2026-06-02-base-path-github-pages.md
	// NOTE: replace USERNAME with the real GitHub account before deploying.
	site: 'https://USERNAME.github.io',
	// `base` MUST match the GitHub repo name (`grimoire-arch`), NOT the dated
	// local folder. The site is served at https://USERNAME.github.io/grimoire-arch/.
	base: '/grimoire-arch',
	integrations: [
		starlight({
			title: 'Grimoire Arch',
			// Theme: default Starlight + a small custom stylesheet, no Tailwind.
			// See docs/adr/2026-06-02-theme-starlight-defaut-customcss.md
			customCss: ['./src/styles/custom.css'],
			// Broken-link canary: Astro/Starlight do NOT fail the build on broken
			// internal links by default. This plugin makes `bun run build` error on
			// them — the real canary for the `guide/annexe-b → ../../adr/` seam and
			// for STORY-008 propagation. See docs/adr/2026-06-03-link-validation-canary.md
			plugins: [starlightLinksValidator()],
			// TODO(/work STORY-002): replace this placeholder sidebar with the
			// final structure once content lands in src/content/docs/:
			//   - group "Guide": explicit ordered items (01..13 + annexes),
			//     NOT autogenerated, to preserve linear reading order.
			//   - group "Coulisses / journal": substrate, subordinate, listed AFTER
			//     the guide so the hero does not drown (autogenerate is fine here).
			// The example content below ships with the template and keeps
			// `bun run build` green; /work STORY-003 removes it.
			sidebar: [
				{
					label: 'Guides',
					items: [{ label: 'Example Guide', slug: 'guides/example' }],
				},
				{
					label: 'Reference',
					items: [{ autogenerate: { directory: 'reference' } }],
				},
			],
		}),
	],
});
